#!/usr/bin/env python3
"""robot/make_import_variants.py -- the two rover MJCFs we hand to the Isaac Sim importer.

    robot/rover.xml  ->  robot/import/rover_train.xml   one articulation, pack merged (training)
                     ->  robot/import/rover_swap.xml    pack as its own body + latch weld (dock)

rover.xml stays the single source of truth; these files are derived from it and
committed so the GPU box needs nothing but a checkout.  Both variants drop what
the importer should not see or would clone into every training env: the ground
plane (Isaac Lab supplies terrain), lights, cameras and the <visual> block.
Everything that defines the physics -- bodies, joints, geoms, materials,
defaults, actuators, sites, sensors, <option> -- is copied unchanged.

rover_train.xml: the pack's geoms move into the chassis at the same pose, so the
machine is one 29.4 kg articulation with the same mass, CoM and inertia as the
latched rover.  No weld, no contact exclude, no second free body.

rover_swap.xml: rover.xml as-is minus the scene.  The importer turns the
`pack_latch` weld into a FixedJoint excluded from the articulation, which the
dock releases at runtime (docs/decisions.md D6).

The solar-panel design (flat as built, fixed tilt, or tilt motor) is an open
owner decision; make it in rover.xml and re-run this script.

Usage:
    python robot/make_import_variants.py            # write both files
    python robot/make_import_variants.py --check    # also compile them with mujoco and
                                                    # compare against rover.xml (mass,
                                                    # CoM, 8 s straight drive)
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROBOT = Path(__file__).resolve().parent
SRC = ROBOT / "rover.xml"
OUT = ROBOT / "import"

HEADER = ("GENERATED by robot/make_import_variants.py from robot/rover.xml -- do not edit; "
          "change rover.xml and re-run. Physics comments live in rover.xml.")

# The pack hangs at (0, 0, -0.0875) in chassis coordinates (rover.xml, pack_latch relpose).
PACK_IN_CHASSIS = (0.0, 0.0, -0.0875)


def _strip_scene(root: ET.Element) -> None:
    """Remove everything that belongs to the scene rather than the robot."""
    world = root.find("worldbody")
    for tag in ("light", "camera"):
        for el in world.findall(tag):
            world.remove(el)
    for geom in world.findall("geom"):
        if geom.get("type") == "plane":
            world.remove(geom)
    for tag in ("visual",):
        for el in root.findall(tag):
            root.remove(el)
    # textures/materials only the removed scene used
    used = {g.get("material") for g in root.iter("geom")} | {s.get("material") for s in root.iter("site")}
    asset = root.find("asset")
    for mat in asset.findall("material"):
        if mat.get("name") not in used:
            asset.remove(mat)
    used_tex = {m.get("texture") for m in asset.findall("material")}
    for tex in asset.findall("texture"):
        if tex.get("name") not in used_tex:
            asset.remove(tex)


def _vec(s: str) -> list[float]:
    return [float(v) for v in s.split()]


def make_swap(src: ET.Element) -> ET.Element:
    root = copy.deepcopy(src)
    _strip_scene(root)
    return root


def make_train(src: ET.Element) -> ET.Element:
    root = copy.deepcopy(src)
    _strip_scene(root)
    world = root.find("worldbody")
    chassis = world.find("body[@name='chassis']")
    pack = world.find("body[@name='pack']")
    for geom in pack.findall("geom"):
        pos = _vec(geom.get("pos", "0 0 0"))
        geom.set("pos", " ".join(f"{p + o:g}" for p, o in zip(pos, PACK_IN_CHASSIS)))
        chassis.append(geom)
    world.remove(pack)
    for tag in ("equality", "contact"):
        for el in root.findall(tag):
            root.remove(el)
    key = root.find("keyframe/key[@name='home']")
    if key is not None:
        key.set("qpos", " ".join(key.get("qpos").split()[:11]))  # chassis free + 4 wheels
    return root


def write(root: ET.Element, path: Path) -> None:
    root.insert(0, ET.Comment(f" {HEADER} "))
    ET.indent(root, space="  ")
    path.parent.mkdir(exist_ok=True)
    path.write_text(ET.tostring(root, encoding="unicode") + "\n", encoding="utf-8", newline="\n")


# ------------------------------------------------------------------ check (needs mujoco)

def _with_ground(xml: str) -> str:
    """The same ground rover.xml measured on, added back for the check only."""
    if 'type="plane"' in xml:  # rover.xml itself already has it
        return xml
    ground = ('<geom name="ground" type="plane" size="10 7 0.1" '
              'friction="0.65 0.005 0.0001" condim="3"/>')
    return xml.replace("<worldbody>", "<worldbody>" + ground, 1)


def _measure(mujoco, xml: str) -> dict:
    import numpy as np
    m = mujoco.MjModel.from_xml_string(_with_ground(xml))
    d = mujoco.MjData(m)
    mujoco.mj_resetDataKeyframe(m, d, m.key("home").id)
    mujoco.mj_forward(m, d)
    total = float(sum(m.body_mass[1:]))
    com_z = float(sum(m.body_mass[i] * d.xipos[i][2] for i in range(1, m.nbody)) / total)
    chassis = m.body("chassis").id
    x0 = float(d.xpos[chassis][0])
    d.ctrl[:] = np.pi  # all four wheels at full forward command
    steps = int(round(8.0 / m.opt.timestep))
    for _ in range(steps):
        mujoco.mj_step(m, d)
    return {"nq": m.nq, "nu": m.nu, "nbody": m.nbody, "neq": m.neq, "mass": total,
            "com_z": com_z, "dx_8s": float(d.xpos[chassis][0]) - x0,
            "scene": (m.nlight, m.ncam)}


def check() -> int:
    import mujoco
    print(f"mujoco {mujoco.__version__}")
    rows = {"rover.xml": _measure(mujoco, SRC.read_text(encoding="utf-8")),
            "rover_train.xml": _measure(mujoco, (OUT / "rover_train.xml").read_text(encoding="utf-8")),
            "rover_swap.xml": _measure(mujoco, (OUT / "rover_swap.xml").read_text(encoding="utf-8"))}
    for name, r in rows.items():
        print(f"  {name:16s} nq={r['nq']:2d} nu={r['nu']} nbody={r['nbody']} neq={r['neq']} "
              f"mass={r['mass']:.2f} kg  CoM z={r['com_z']:.4f} m  8 s drive dx={r['dx_8s']:.3f} m  "
              f"lights/cams={r['scene']}")
    ref, ok = rows["rover.xml"], True
    for name in ("rover_train.xml", "rover_swap.xml"):
        r = rows[name]
        for key, tol in (("mass", 1e-6), ("com_z", 1e-4), ("dx_8s", 0.02)):
            if abs(r[key] - ref[key]) > tol:
                ok = False
                print(f"FAIL  {name}: {key} {r[key]:.4f} vs rover.xml {ref[key]:.4f} (tol {tol})")
        if r["scene"] != (0, 0):
            ok = False
            print(f"FAIL  {name}: still has lights/cameras {r['scene']}")
    if abs(ref["mass"] - 29.4) > 1e-6:
        ok = False
        print(f"FAIL  rover.xml mass {ref['mass']:.3f} kg, SPEC says 29.4")
    print("VARIANTS OK" if ok else "VARIANTS FAILED")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="compile and compare with mujoco")
    args = ap.parse_args()
    # rover.xml's comments contain "--", which MuJoCo tolerates but strict XML does not;
    # the generated files carry no comments anyway.
    text = re.sub(r"<!--.*?-->", "", SRC.read_text(encoding="utf-8"), flags=re.S)
    src = ET.fromstring(text)
    write(make_train(src), OUT / "rover_train.xml")
    write(make_swap(src), OUT / "rover_swap.xml")
    print(f"wrote {OUT / 'rover_train.xml'}\nwrote {OUT / 'rover_swap.xml'}")
    return check() if args.check else 0


if __name__ == "__main__":
    sys.exit(main())
